//;  CMT2300A Configuration File
//;  Generated by CMOSTEK RFPDK 1.41 Beta
//;  2017.01.24 18:18
//;---------------------------------------
//; Mode                    = Advanced
//; Part Number             = CMT2300A
//; Frequency               = 868.350 MHz
//; Xtal Frequency          = 26.0000 MHz
//; Demodulation            = FSK
//; AGC                     = On
//; Data Rate               = 2.4 kbps
//; Deviation               = 4.8 kHz
//; Tx Xtal Tol.            = 20 ppm
//; Rx Xtal Tol.            = 20 ppm
//; Tx Power                = +13 dBm
//; Gaussian BT             = NA
//; Bandwidth               = Auto-Select kHz
//; CDR Type                = Tracing
//; CDR DR Range            = +/-12.5%
//; AFC                     = On
//; AFC Method              = Auto-Select
//; Data Representation     = 0:F-low 1:F-high
//; Rx Duty-Cycle           = Off
//; Tx Duty-Cycle           = Off
//; Sleep Timer             = Off
//; Sleep Time              = NA
//; Rx Timer                = Off
//; Rx Time T1              = NA
//; Rx Time T2              = NA
//; Rx Exit State           = SLEEP
//; Tx Exit State           = SLEEP
//; SLP Mode                = Disable
//; RSSI Valid Source       = PJD
//; PJD Window              = 8 Jumps
//; LFOSC Calibration       = On
//; Xtal Stable Time        = 155 us
//; RSSI Compare TH         = NA
//; Data Mode               = Packet
//; Whitening               = Disable
//; Whiten Type             = NA
//; Whiten Seed Type        = NA
//; Whiten Seed             = NA
//; Manchester              = Disable
//; Manchester Type         = NA
//; FEC                     = Disable
//; FEC Type                = NA
//; Tx Prefix Type          = 0
//; Tx Packet Number        = 1
//; Tx Packet Gap           = 32
//; Fifo Threshold          = 16
//; Packet Type             = Variable Length
//; Node-Length Position    = First Node, then Length
//; Payload Bit Order       = Start from msb
//; Preamble Rx Size        = 2
//; Preamble Tx Size        = 16
//; Preamble Value          = 85
//; Preamble Unit           = 8-bit
//; Sync Size               = 3-byte
//; Sync Value              = 11152852
//; Sync Tolerance          = None
//; Sync Manch              = Disable
//; Node ID Size            = NA
//; Node ID Value           = NA
//; Node ID Mode            = None
//; Node ID Err Mask        = NA
//; Node ID Free            = NA
//; Payload Length          = 32
//; CRC Options             = CCITT-16
//; CRC Seed                = 0 crc_seed
//; CRC Range               = Entire Payload
//; CRC Swap                = Start From MSB
//; CRC Bit Inv             = Normal
//; CRC Bit Order           = Start From bit 15
//; Dout Mute               = Off
//; Dout Adjust Mode        = Disable
//; Dout Adjust Percentage  = NA
//; Collision Detect        = Off
//; Collision Detect Offset = NA
//; RSSI Detect Mode        = Always
//; RSSI Filter Setting     = No Filtering
//; RF Performance          = Low
//; LBD Threshold           = 2.4 V
//; System Clock Output     = Off
//; System Clock Frequency  = NA
//; RSSI Offset             = 0
//; RSSI Offset Sign        = 0
//;---------------------------------------
//;  The following are the Register contents
//;---------------------------------------

unsigned char FreqString[]   = {"Freq: 868.350MHz"};                                
unsigned char BRnDevString[] = {"Dev:4.8K BR:2.4K"}; 
unsigned char PowerString[]  = {"Pwr: +13dBm     "};


//[CMT Bank]
unsigned int CMTBank[12] = {
/*
0x0000,
0x0166,
0x026C,
0x037C,
0x04F0,
0x0580,
0x0614,
0x0708,
0x0831,
0x0903,
0x0A00,
0x0B00,
*/
    0x00,
    0x66,
    0xEC,
    0x1D,//20dbm //0x1C,
    0xF0,
    0x80,
    0x14,
    0x08,
    0x91,
    0x02,
    0x02,
    0xD0,
};

//[System Bank]
unsigned int SystemBank[12] = {
/*0x0CA5,
0x0DE0,
0x0E30,
0x0F00,
0x1000,
0x11F4,
0x1210,
0x13E2,
0x1442,
0x1520,
0x1600,
0x1781,*/
    0xA5,
    0xE0,
    0x35,
    0x00,
    0x00,
    0xF4,
    0x10,
    0xE2,
    0x42,
    0x20,
    0x00,
    0x81,
};

//[Frequency Bank]
unsigned int FrequencyBank[8] = {
/*0x1842,
0x1916,
0x1A16,
0x1B8D,
0x1C42,
0x1D0B,
0x1EBD,
0x1F1C,*/
    0x42,
    0x71,
    0xCE,
    0x1C,
    0x42,
    0x5B,
    0x1C,
    0x1C,
};

//[Data Rate Bank]
unsigned int DataRateBank[24] = {
/*0x2032,
0x2118,
0x2210,
0x2399,
0x24C1,
0x259B,
0x2606,
0x270A,
0x289F,
0x2939,
0x2A29,
0x2B28,
0x2CC0,
0x2D51,
0x2E2A,
0x2F53,
0x3000,
0x3100,
0x32B4,
0x3300,
0x3400,
0x3501,
0x3600,
0x3700,*/
    0x32,
    0x18,
    0x10,
    0x99,
    0xF1,
    0x9B,
    0x2C,
    0x0A,
    0x9F,
    0x39,
    0x29,
    0x29,
    0xC0,
    0x51,
    0x2A,
    0x53,
    0x00,
    0x00,
    0xB4,
    0x00,
    0x00,
    0x01,
    0x00,
    0x00,
};

//[Baseband Bank]
unsigned int BasebandBank[29] = {
/*0x3812,
0x3910,
0x3A00,
0x3B55,
0x3C04,
0x3D00,
0x3E00,
0x3F00,
0x4000,
0x4100,
0x42D4,
0x432D,
0x44AA,
0x4501,
0x461F,
0x4700,
0x4800,
0x4900,
0x4A00,
0x4B00,
0x4C01,
0x4D00,
0x4E00,
0x4F00,
0x5000,
0x5100,
0x5200,
0x5320,
0x5410,*/
    0x12,
    0x08,
    0x00,
    0xAA,
    0x04,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xD4,
    0x2D,
    0xAA,
    0x00,//0x01,//¡À?D??a0¡ê?¡¤??¨°¨ºy?Y3?¡ä¨ª
    0x1F,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x60,
    0xFF,
    0x00,
    0x00,
    0x1F,
    0x10,//Len payload
};

//[TX Bank]
unsigned int TXBank[11] = {
/*0x5550,
0x5683,
0x5701,
0x5800,
0x5944,
0x5AD0,
0x5B00,
0x5C53,
0x5D0C,
0x5E3F,
0x5F7F,*/
    0x50,
    0x0E,
    0x16,
    0x00,
    0x42,
    0xB0,
    0x00,
    0x8A,
    0x18,
    0x3F,
    0x7F,
};

//;---------------------------------------
//;  The following is the CRC result for
//;  the above Register contents
//;---------------------------------------
//0xBBA2
